name: run-tests
on: [push, pull_request]
jobs:
    test-part-1:
        name: Test part 1
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Java 8
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '8'
            - name: Run the tests
              run: |
                make test-part-1
    test-part-2:
        name: Test part 2
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Java 8
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '8'
            - name: Run the tests
              run: |
                make test-part-2
